name: Screenshot
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  web-screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: swinton/screenshot-website@v1.x
        with:
          source: https://inimicalpart.com
          destination: site.screenshot.svg
          full-page: true
  
